name: stable-diffusion-nf
channels:
  - defaults
  - conda-forge
  - pytorch-lts
  - anaconda
  - huggingface
dependencies:
  - huggingface_hub
  - transformers
  - diffusers==0.2.4
  - pytorch
  - torchvision
  - tqdm
  - pillow
  - matplotlib
  - numpy

